name: Run Discord Bot

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t peru-leni-jeevi-bot .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/peru-leni-jeevi-bot

      - name: Run Docker container
        run: docker run -d -e DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} ghcr.io/${{ github.repository_owner }}/peru-leni-jeevi-bot
