name: Run Discord Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Debug HEADERS
      run: echo "HEADERS: $HEADERS"
      env:
        HEADERS: ${{ secrets.HEADERS }}
    - name: Run bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DEEPSEEK: ${{ secrets.DEEPSEEK }}
        HEADERS: ${{ secrets.HEADERS }}
      run: python main.py
