name: Deploy and Run Bot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set working directory
        uses: actions/checkout@v3
        working-directory: ./frontend

      - name: Verify package-lock.json exists
        run: |
          ls -la ./
          cat ./package-lock.json

      - name: Print npm cache path
        run: npm config get cache

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Error handling for build-and-deploy
        if: failure()
        run: echo "Build and deploy job failed."

      - name: Notify on build-and-deploy failure
        if: failure()
        run: echo "Sending notification for build-and-deploy failure."

  run-bot:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify requirements.txt exists
        run: |
          ls -la
          cat requirements.txt

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Build and run bot in Docker
        run: |
          docker build -t peru-leni-jeevi .
          docker run -d -p 5000:5000 \
            -e DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} \
            -e COOKIES=${{ secrets.COOKIES }} \
            -e DEEPSEEK=${{ secrets.DEEPSEEK }} \
            peru-leni-jeevi

      - name: Error handling for run-bot
        if: failure()
        run: echo "Run bot job failed."

      - name: Notify on run-bot failure
        if: failure()
        run: echo "Sending notification for run-bot failure."
